### ISSUE TITLE
Data issue when creating multiple ddslick dropdown with classes

### ISSUE THREAD

**Issue by prashantchaudhary** [prashantchaudhary/ddslick#11]
When multiple ddslick dropdown are created on a page using 'class', each 'ddslick' dropdown is populated with content from from the previous ddslick in addition to its own. Reported on plugin's page at http://designwithpc.com/Plugins/ddSlick

**Comment by prashantchaudhary** [comment]
Looking at the code for Pull Request #18 seems like it fixed this bug. Please bring up if it doesn't still solves this issue.

**Comment by caraffa** [comment]
I'm having the same problem. Has this issue been fixed?
