### ISSUE TITLE
Doesn't work for multiple selects

### ISSUE THREAD

**Issue by EtienneDepaulis** [prashantchaudhary/ddslick#4]
If this plugin is used on a class, it doesn't behave properly :s (all the options from the different selects are added to each select :s)

**Comment by davidspiess** [comment]
Having the same issue.

**Comment by lu3do** [comment]
use this as a workaround

``` javascript
$("select.ddslick").each(function(){
            $(this).ddslick({
                showSelectedHTML: false  
            });
        });
```

**Comment by peterbee** [comment]
This workaround doesn't seem to fix the [missing options problem, as noted here](https://github.com/prashantchaudhary/ddslick/commit/ff84358e6ccccbc76bc28f299fa5acbb2efcb0ab#commitcomment-3072494).

**Comment by romanglom** [comment]
I found a workaround to fix it.

```
$('.your-class').each(function (index, element) {
            $(element).ddslick({
                ... options ...
            });
        });
```

**Comment by lu3do** [comment]
@romanglom that's the same workaround I posted 3 years ago.

**Comment by romanglom** [comment]
@ludo-h You are right!! I didn't see it =)
