### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: <div

### ISSUE THREAD

**Issue by dittodhole** [prashantchaudhary/ddslick#48]
introduced with commit 5c1eca60c9 where

```
var original = obj, placeholder = $('<div id="' + obj.attr('id') + '"></div>');
```

got replaced by

```
var original = obj, placeholder = $('<div').attr('id', obj.attr('id') + '-dd-placeholder');
```

**Comment by gpapin** [comment]
Thanks for the correction ! :)  this should be merge by now ...

**Comment by Jmeyering** [comment]
+1 for merging this in!

**Comment by dittodhole** [comment]
@0x1gene nope, it is not ... current HEAD is 5c1eca6, which was done on Jul-12-2013 ...

**Comment by gpapin** [comment]
Yes sorry for the misunderstanding, I know this fix is not merge yet, I meant "The author should have merge it"

**Comment by dittodhole** [comment]
@0x1gene ;) thanks for that clarification...!

**Comment by ghost** [comment]
This issue still persists with the bower package of ddslick. Please fix!

**Comment by a2wd** [comment]
The issue is fixed in the minified/production but not fixed in the development version.

**Comment by lucascaton** [comment]
@prashantchaudhary could you please merge it? Thanks.

**Comment by dittodhole** [comment]
closing due to lack of interest.
